# Generated by Django 2.2.4 on 2019-11-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=5000)),
                ('delete_yn', models.CharField(max_length=1)),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
                ('delete_at', models.DateField()),
            ],
            options={
                'db_table': 'tbl_post',
            },
        ),
        migrations.CreateModel(
            name='PostMemory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kanji', models.CharField(max_length=255)),
                ('hiragana', models.CharField(max_length=255)),
                ('hangul', models.CharField(max_length=255)),
                ('delete_yn', models.CharField(max_length=1)),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
                ('delete_at', models.DateField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post')),
            ],
            options={
                'db_table': 'tbl_post_memory',
            },
        ),
    ]
