# Generated by Django 2.2.4 on 2019-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191129_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delete_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmemory',
            name='delete_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmemory',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
