# Generated by Django 2.2.4 on 2019-11-29 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191130_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2019, 11, 30, 0, 18, 40, 953361)),
        ),
        migrations.AlterField(
            model_name='postmemory',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2019, 11, 30, 0, 18, 40, 954360)),
        ),
    ]
